### ISSUE TITLE
the speed of OCR slowly

### ISSUE THREAD

**Issue by chostyouwang** [Unstructured-IO/unstructured-api#211]
Is there a parallel parsing method available to improve the speed of OCR recognition?

**Comment by cragwolfe** [comment]
There aren't quick wins for OCR speedups right now. One can process PDF pages in parallel by setting the env var UNSTRUCTURED_PARALLEL_MODE_URL to point to a cluster of hosts running this API.
Otherwise, one would have to dig into tesseract optimizations (or even replacing tesseract in portions of the unstructured library).

**Comment by chostyouwang** [comment]
Is the setting UNSTRUCTURED_PARALLEL_MODE_URL configured in the environment variable? I understand that the URL location keeps changing, right?

**Comment by chostyouwang** [comment]
I don't quite understand how to configure UNSTRUCTURED_PARALLEL_MODE_URL either.
